POST http://localhost:3000/createProject 
Content-Type: application/json

{
    "titre":"Projet Fullstack",
    "descriptionIntro":"Projet Fullstack",
    "description":"Projet Fullstack",
    "ListeMotCle":["Projet Fullstack"],
    "lienImage":"https://www.google.com",
    "lienGitHub":"https://www.google.com",
    "listeImmages":["https://www.google.com"],
    "nbVue":0

    
}

###

PUT http://localhost:3000/api/projects/6621342a7c30cb64430a26ea
Content-Type: application/json

{
    "titre":"Projet Fullstackclement",
    "descriptionIntro":"Projet Fullstack",
    "description":"Projet Fullstack",
    "ListeMotCle":["Projet Fullstack"],
    "lienImage":"https://www.google.com",
    "lienGitHub":"https://www.google.com",
    "listeImmages":["https://www.google.com"],
    "nbVue":0
}


